version: "3.8"

services:
  database:
    build: Database/.
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 9090:8080
  queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
